/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

/**
 *
 * @author Ruhan
 */
public class Choice_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Choice_JFrame
     */
    public Choice_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Display_Personal_Bookings = new javax.swing.JButton();
        btn_Create_Booking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Display_Personal_Bookings.setText("Personal Bookings Made");
        btn_Display_Personal_Bookings.setToolTipText("");
        btn_Display_Personal_Bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Display_Personal_BookingsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Display_Personal_Bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 191, 86));

        btn_Create_Booking.setText("Create Booking");
        btn_Create_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Create_BookingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Create_Booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 191, 86));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Create_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Create_BookingActionPerformed
        // TODO add your handling code here:
        Create_Booking mb = new Create_Booking();
        mb.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_Create_BookingActionPerformed

    private void btn_Display_Personal_BookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Display_Personal_BookingsActionPerformed
        // TODO add your handling code here:
        
        Client_personal_Booking_view cpbv = new Client_personal_Booking_view();
        cpbv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Display_Personal_BookingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choice_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choice_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choice_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choice_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choice_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Create_Booking;
    private javax.swing.JButton btn_Display_Personal_Bookings;
    // End of variables declaration//GEN-END:variables
}
